#### Using the titanic data, in your classification-exercises repository, create a notebook, decision_tree.ipynb where you will do the following:

In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree
import sklearn.metrics
from sklearn.model_selection import train_test_split
import acquire as aq
import prepare

In [168]:
df = aq.get_titanic_data()

In [169]:
df = prepare.prep_titanic(df)
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  \
0         0       3    male  22.0      1      0   7.2500        S   
1         1       1  female  38.0      1      0  71.2833        C   
2         1       3  female  26.0      0      0   7.9250        S   
3         1       1  female  35.0      1      0  53.1000        S   
4         0       3    male  35.0      0      0   8.0500        S   

   embark_town  alone  sex_male  embark_town_Queenstown  \
0  Southampton      0         1                       0   
1    Cherbourg      0         0                       0   
2  Southampton      1         0                       0   
3  Southampton      0         0                       0   
4  Southampton      1         1                       0   

   embark_town_Southampton  
0                        1  
1                        0  
2                        1  
3                        1  
4                        1

What is your baseline prediction? What is your baseline accuracy? remember: your baseline prediction for a classification problem is predicting the most prevelant class in the training dataset (the mode). When you make those predictions, what is your accuracy? This is your baseline accuracy.

In [170]:
df.survived.value_counts()

0    549
1    342
Name: survived, dtype: int64

In [171]:
df['bl_survival_pred'] = 0

In [172]:
(df.survived == df.bl_survival_pred).mean()

0.6161616161616161

BL prediction: survived = 0
BL accuracy: .62

In [128]:
train_val, test = train_test_split(
    df,
    train_size = 0.8,
    random_state = 1349,
    stratify = df['survived']
)

train, validate = train_test_split(
    train_val,
    train_size = 0.7,
    random_state = 1349,
    stratify = train_val['survived']
)

In [129]:
train.shape, validate.shape, test.shape

((498, 14), (214, 14), (179, 14))

In [173]:
baseline_accuracy = (train.survived == train.bl_survival_pred).mean()
baseline_accuracy

0.6164658634538153

Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [130]:
x_cols = train.columns.to_list()
y_cols = 'survived'

In [131]:
x_cols.remove('survived')
x_cols.remove('bl_survival_pred')
x_cols.remove('sex')
x_cols.remove('embarked')
x_cols.remove('embark_town')

In [132]:
x_cols

['pclass',
 'age',
 'sibsp',
 'parch',
 'fare',
 'alone',
 'sex_male',
 'embark_town_Queenstown',
 'embark_town_Southampton']

In [133]:
# make the thing
clf1 = DecisionTreeClassifier()

# fitting the thing
clf1.fit(train[x_cols], train[y_cols])

# use the thing
model_1_preds = clf1.predict(train[x_cols])

In [134]:
model_1_preds

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,

Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [135]:
print('------------------model score-----------------------')
print(clf1.score(train[x_cols], train[y_cols]))
print('----------------confusion matrix---------------------')
print(confusion_matrix(train[y_cols], model_1_preds))
print('--------------classification report-------------------')
print(classification_report(train[y_cols], model_1_preds))

------------------model score-----------------------
0.9839357429718876
----------------confusion matrix---------------------
[[306   1]
 [  7 184]]
--------------classification report-------------------
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       307
           1       0.99      0.96      0.98       191

    accuracy                           0.98       498
   macro avg       0.99      0.98      0.98       498
weighted avg       0.98      0.98      0.98       498



Compute: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [136]:
print(accuracy_score(train[y_cols], model_1_preds))

0.9839357429718876


In [137]:
cm = confusion_matrix(train[y_cols], model_1_preds)

In [138]:
TP = cm[0][0]
FN = cm[0][1]
FP = cm[1][0]
TN = cm[1][1]

In [140]:
print(f'The TP rate is {TP}')
print(f'The FP rate is {FP}') 
print(f'The TN rate is {TN}')
print(f'The FN rate is {FN}')

The TP rate is 306
The FP rate is 7
The TN rate is 184
The FN rate is 1


In [141]:
print(sklearn.metrics.precision_recall_fscore_support(train[y_cols], model_1_preds, average='binary'))

(0.9945945945945946, 0.9633507853403142, 0.9787234042553191, None)


Run through steps 2-4 using a different max_depth value.

In [151]:
# make the thing
clf2 = DecisionTreeClassifier(max_depth = 2)

# fitting the thing
clf2.fit(train[x_cols], train[y_cols])

# use the thing
model_2_preds = clf2.predict(train[x_cols])

In [152]:
print('------------------model score-----------------------')
print(clf2.score(train[x_cols], train[y_cols]))
print('----------------confusion matrix---------------------')
print(confusion_matrix(train[y_cols], model_2_preds))
print('--------------classification report-------------------')
print(classification_report(train[y_cols], model_2_preds))

------------------model score-----------------------
0.8012048192771084
----------------confusion matrix---------------------
[[304   3]
 [ 96  95]]
--------------classification report-------------------
              precision    recall  f1-score   support

           0       0.76      0.99      0.86       307
           1       0.97      0.50      0.66       191

    accuracy                           0.80       498
   macro avg       0.86      0.74      0.76       498
weighted avg       0.84      0.80      0.78       498



In [153]:
print(accuracy_score(train[y_cols], model_2_preds))

0.8012048192771084


In [154]:
cm2 = confusion_matrix(train[y_cols], model_2_preds)

In [155]:
TP2 = cm2[0][0]
FN2 = cm2[0][1]
FP2 = cm2[1][0]
TN2 = cm2[1][1]

In [156]:
print(f'The model 2 TP rate is {TP2}')
print(f'The model 2 FP rate is {FP2}') 
print(f'The model 2 TN rate is {TN2}')
print(f'The model 2 FN rate is {FN2}')

The model 2 TP rate is 304
The model 2 FP rate is 96
The model 2 TN rate is 95
The model 2 FN rate is 3


In [157]:
print(sklearn.metrics.precision_recall_fscore_support(train[y_cols], model_2_preds, average='binary'))

(0.9693877551020408, 0.4973821989528796, 0.657439446366782, None)


Which model performs better on your in-sample data?

Model 1, 0.98 vs. .80 model score

Which model performs best on your out-of-sample data, the validate set?

In [161]:
print('Accuracy of Model 1 on validate set: {:.2f}'
     .format(clf1.score(validate[x_cols], validate[y_cols])))

Accuracy of Model 1 on validate set: 0.73


In [162]:
print('Accuracy of Model 2 on validate set: {:.2f}'
     .format(clf2.score(validate[x_cols], validate[y_cols])))

Accuracy of Model 2 on validate set: 0.76


In [166]:
# And since accuracy isn't everything

# Produce y_predictions that come from the validate[x_cols]
y_pred1 = clf1.predict(validate[x_cols])
y_pred2 = clf1.predict(validate[x_cols])

# Compare actual y values (from validate) to predicted y_values from the model run on X_validate
print('--------------model 1 classification report-------------------')
print(classification_report(validate[y_cols], y_pred1))
print('--------------model 2 classification report-------------------')
print(classification_report(validate[y_cols], y_pred2))

--------------model 1 classification report-------------------
              precision    recall  f1-score   support

           0       0.79      0.76      0.78       132
           1       0.64      0.68      0.66        82

    accuracy                           0.73       214
   macro avg       0.72      0.72      0.72       214
weighted avg       0.73      0.73      0.73       214

--------------model 2 classification report-------------------
              precision    recall  f1-score   support

           0       0.79      0.76      0.78       132
           1       0.64      0.68      0.66        82

    accuracy                           0.73       214
   macro avg       0.72      0.72      0.72       214
weighted avg       0.73      0.73      0.73       214



Work through these same exercises using the Telco dataset.
Experiment with this model on other datasets with a higher number of output classes.